### PR TITLE
Try to fix the incompatible MPL's _hold

### PR DESCRIPTION
**Pull request by mrakitin**
This was reported by @afluerasu. The patch should fix the issue.

### CODE REVIEW

**Comment by danielballan** [comment]
Should `axes.cla()` have been removed, or always run?

**Comment by mrakitin** [comment]
Good point. Last time we discussed it with @tacaswell, the decision was to only comment the places where `_hold` was used, which I did by the direct modification of the installed sources. This update is going to be a more sustainable solution.

**Comment by danielballan** [comment]
OK. From that comment it's obvious to me whether he meant to _remove_ `axes.cla()` or to dedent it and just remove the `axes._hold` bit.

**Comment by tacaswell** [comment]
`ax.cla()` should never be run.

**Comment by mrakitin** [comment]
Maybe a follow-up PR should be to just remove those 2 lines :)

**Pull request merged**
